div 2 A:
https://codeforces.com/contest/1797/problem/A
https://codeforces.com/contest/1805/problem/A
https://codeforces.com/contest/1808/problem/A
https://codeforces.com/contest/1798/problem/A
https://codeforces.com/contest/1802/problem/A
https://codeforces.com/contest/1794/problem/A
https://codeforces.com/contest/1789/problem/A
https://codeforces.com/contest/1786/problem/A1
https://codeforces.com/contest/1778/problem/A
https://codeforces.com/contest/1780/problem/A
https://codeforces.com/contest/1777/problem/A
https://codeforces.com/contest/1775/problem/A1
https://codeforces.com/contest/1768/problem/A
https://codeforces.com/contest/1731/problem/A
https://codeforces.com/contest/1763/problem/A
https://codeforces.com/contest/1762/problem/A
https://codeforces.com/contest/1771/problem/A
https://codeforces.com/contest/1758/problem/A
https://codeforces.com/contest/1748/problem/A
https://codeforces.com/contest/1747/problem/A
https://codeforces.com/contest/1754/problem/A
https://codeforces.com/contest/1736/problem/A
https://codeforces.com/contest/1735/problem/A
https://codeforces.com/contest/1730
https://codeforces.com/contest/1734/problem/A
https://codeforces.com/contest/1733/problem/A
https://codeforces.com/contest/1717/problem/A
https://codeforces.com/contest/1715/problem/A
https://codeforces.com/contest/1720/problem/A
https://codeforces.com/contest/1719/problem/A
https://codeforces.com/contest/1712/problem/A
https://codeforces.com/contest/1713/problem/A
https://codeforces.com/contest/1711/problem/A
https://codeforces.com/contest/1706/problem/A
https://codeforces.com/contest/1708/problem/A
https://codeforces.com/contest/1705/problem/A
https://codeforces.com/contest/1699/problem/A
https://codeforces.com/contest/1698/problem/A
https://codeforces.com/contest/1700/problem/A